### ISSUE TITLE
Allow inactive channels to be visible in the web interface

### ISSUE THREAD

**Issue by ipmb** [BotBotMe/botbot-web#135]
This is an edge-case for gittip/graitpay. See https://github.com/gratipay/inside.gratipay.com/issues/153. The gittip channel is no longer active, but it has old logs stored that they still want access to and have old links work. I'd rather not add another boolean to the model for this one-off case. 

@yml or @vbabiy Would it work to change the channel_id on the old logs and then put a redirect in at Nginx?

**Comment by whit537** [comment]
Thanks for looking into this! :-)

**Comment by ipmb** [comment]
I merged the gittip logs into gratipay and setup a redirect. The link I tested works although I may have uncovered another bug in the process: #136

**Comment by whit537** [comment]
@ipmb Lovely, thank you! :-)
