### ISSUE TITLE
Allow downloading channel logs in plain text

### ISSUE THREAD

**Issue by singingwolfboy** [BotBotMe/botbot-web#141]
BotBot.me is a *fantastic* service, thanks so much for providing it! However, it would be really nice to be able to analyze the messages in a channel log, which requires downloading them in plain text rather than HTML. Is this something that you could implement? Maybe instead of visiting `https://botbot.me/network/channel/` to get an HTML view, a client could visit `https://botbot.me/network/channel/date-string.txt` to get a plain-text representation. For example, a URL could be `https://botbot.me/freenode/edx-code/2015-04-30.txt`.

**Comment by pdurbin** [comment]
:+1:

This is one of my favorite features of https://github.com/moritz/ilbot

http://irclog.perlgeek.de/crimsonfu/2015-12-02 can be rendered as http://irclog.perlgeek.de/crimsonfu/2015-12-02/text for example.

This allows for "data liberation", if you will. I use this script to download all the logs for safe keeping: https://github.com/crimsonfu/crimsonfu.github.com/blob/master/bin/logfetch.pl

**Comment by unbracketed** [comment]
In the past we've discussed making the log data more easily accessible in text format (for example, served from cloud storage). This would require (or encourage) some new architecture and unfortunately we don't have any plans for that at this time. If that changes we'll let you know.

There is a URL pattern you can use to access logs as text and this could be the starting point for what you might be after.  For example: https://botbot.me/freenode/stripe/2016-05-01.log

**Comment by domenkozar** [comment]
Would be lovely to get them in a zip file, now I have to crawl a few years of days :)

**Comment by ipmb** [comment]
Thanks for the feedback @domenkozar. We probably won't have the bandwidth to add this functionality anytime soon.
