### ISSUE TITLE
Messages starting with ACTION interpreted as /me

### ISSUE THREAD

**Issue by LeoVerto** [BotBotMe/botbot-web#151]
This is a fairly minor bug but while working on some BotBot modifications, I discovered that when a user sends a message starting with "ACTION", the message is logged as a /me.

For example these messages:
> /me is currently creating an issue
> ACTION is currently creating an issue

resulted in this: https://botbot.me/freenode/lincolnloop/#48125559

This might actually be a bug of botbot-bot as the raw messages the plugins get seem to be exactly the same.

**Comment by ipmb** [comment]
I think you're right. The logger doesn't do any manipulation of this. Moved to https://github.com/BotBotMe/botbot-bot/issues/36
