### ISSUE TITLE
Public but non-active channel has inaccessible logs

### ISSUE THREAD

**Issue by Freso** [BotBotMe/botbot-web#152]
If a channel is decommissioned but you want to keep the logs around, you may want to de-active the channel, so the bot doesn't stick around in it anymore either. However, this deactivation causes the channel to disappear completely from the user-facing web interface, meaning that the logs are no longer accessible. See e.g., http://liveweb.archive.org/web/20150914221458/http://chatlogs.metabrainz.org/brainzbot/musicbottle/ (that's a public but deactivated channel)

**Comment by vbabiy** [comment]
Last part is update the Bot

**Comment by Freso** [comment]
:heart: @vbabiy - thank you for taking this on! :)

**Comment by vbabiy** [comment]
This has been merged in to master.
