### ISSUE TITLE
Search for all messages of a particular user

### ISSUE THREAD

**Issue by dufferzafar** [BotBotMe/botbot-web#156]
Currently there's a search feature that searches for keywords in the irc logs. For eg: https://botbot.me/freenode/sublimetext/search/?q=sublime

I feel that there should also be a way of searching for all messages by a particular user. Something like: https://botbot.me/freenode/sublimetext/search/?user=FichteFoll [non existent link] 

We could then extend this search functionality by merging the above two parameters to find something said by a particular user. https://botbot.me/freenode/sublimetext/search/?q=sublime&user=FichteFoll [non existent link]

By the way, thanks for an awesome service :smiley_cat:

**Comment by marcoms** [comment]
This would be incredibly useful for me since I always need to recall the answers to questions I've asked.

**Comment by ipmb** [comment]
It should already be there, see https://github.com/BotBotMe/botbot-web/issues/21
