### ISSUE TITLE
Using the component to only extract a channel historical logs

### ISSUE THREAD

**Issue by Ahmed-Abouzeid** [BotBotMe/botbot-web#157]
Hello,

Which part in the component I can use to extract a channel historical logs. I am working on a dataset creation project that should create IRC datasets for deep learning.

Thanks

**Comment by ipmb** [comment]
If you are running your own instance, you could extract them directly from the database. Otherwise, there is a plain-text log view you may find helpful https://github.com/BotBotMe/botbot-web/blob/master/botbot/apps/logs/urls.py#L8-L9
