### ISSUE TITLE
No SASL

### ISSUE THREAD

**Issue by holoc** [BotBotMe/botbot-web#165]
Hi, I'm trying to have the bot connect to Freenode, but the server response says that I have to connect by SASL access in order to connect. This is what I get from the honcho command window:
:verne.freenode.net NOTICE * :*** Found your hostname
:verne.freenode.net NOTICE * :*** No Ident response
:verne.freenode.net 451 * :You have not registered
:verne.freenode.net NOTICE oklogger :*** Notice -- You need to identify via SASL to use this server
 ERROR :Closing Link: ec2*******.compute.amazonaws.com (SASL access only)
I've checked that the registered Nick works using MIRC, but the Nick doesn't seem to be recognized through the bot trying to connect to Freenode. 
Anyone have a clue where I might've gone wrong?

**Comment by holoc** [comment]
https://github.com/flackr/circ/issues/300
I guess my amazon server is on the blacklist...

**Comment by holoc** [comment]
https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/JENKINS-33667

**Comment by ipmb** [comment]
MOved to https://github.com/BotBotMe/botbot-bot/issues/46
