### ISSUE TITLE
Doesnt work link of irc-guide https://github.com/BotBotMe/irc-guide

### ISSUE THREAD

**Issue by kangarooo** [BotBotMe/botbot-web#169]
https://github.com/BotBotMe/irc-guide
Written 
This was integrated into botbot-web: https://github.com/BotBotMe/botbot-web/blob/master/botbot/templates/irc-guide.html

Link dont work

**Comment by ipmb** [comment]
Links removed. The guide isn't in an open source repo at the moment, but you can find it in the git history here: https://github.com/BotBotMe/botbot-web/commit/dff7c505beef71ca898603f10ec84f9ef93f779a
