### ISSUE TITLE
Reset Migrations / Drop references to hstore

### ISSUE THREAD

**Issue by unbracketed** [BotBotMe/botbot-web#94]
We removed use of django-hstore since it was problematic in production. Unfortunately the initial migration definitions reference hstore. We should reset the migrations or manually patch the migration files

**Comment by gaker** [comment]
addressed here: https://github.com/BotBotMe/botbot-web/pull/97

**Comment by gaker** [comment]
6ba4a13e95e4399d2b3c2f75b422b2c63adb630d
